print ('naaminvoer')
name = input('geef jouw naam: ')
print('Hallo '+ name)
print ('adres')
adres = input ('Geef adres hier: ')
print (adres)
print ('postcodeinvoer')
postcode = input ('Geef postcode hier: ')
print (postcode)
print ('woonplaatsinvoer')
woonplaats = input ('geef woonplaats hier: ')
print (woonplaats)
print ("- ---------------------------------------------------")
print ("|  Naam       : " + name)
print ("|  adres      : " + adres)
print ("|  postcode   : " + postcode)
print ("|  woonplaats : " + woonplaats)
print (" ----------------------------------------------------")