print ('naaminvoer')
name = input('geef jouw naam')
print('Hallo '+ name)
print ('adres')
adres = input ('Geef adres hier')
print (adres)
print ('postcodeinvoer')
postcode = input ('Geef postcode hier')
print (postcode)
print ('woonplaatsinvoer')
woonplaats = input ('geef woonplaats hier')
print ("- ---------------------------------------------------")
print ("|  Naam      :") 
(print (name))
print ("|  adres     :") 
(print (adres)) 
print ("|  postcode  :") 
(print (postcode)) 
print ("|  woonplaats:") 
(print (woonplaats)) 
print (" ----------------------------------------------------")